server:
  port: 8080

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 50MB
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pet?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  thymeleaf:
    cache: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
